spring.application.name=kodnestSalesSavvy
server.port = 9090
spring.datasource.url=jdbc:mysql://localhost:3306/salessavvy
spring.datasource.username=root
spring.datasource.password=222003
spring.jpa.hibernate.ddl-auto=update
spring.security.enabled = false

jwt.secret=your-very-long-secure-secret-key-for-production-12345678901234567890
jwt.expiration=3600000

razorpay.key_id = rzp_test_SSOPBaeglF9OD0 
razorpay.key_secret = G7yY3wgsTq3Ag6ZWzCk6uEWc